#!/bin/bash
JAVA=java
JAR=${JARDIR}loaders_dna-bundled-0.5.jar
#CONFIG_FILE = "ccu_heineken-config.properties"

STARTTIME=$(date +%s)
echo "Starting today daily run - API to BigQuery: `date`"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - -config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - -config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - -config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - -config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - -config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - -config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - -config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - -config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - -config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - -config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - -config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - -config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - -config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - -config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - -config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - -config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - -config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_isenbeck-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_isenbeck-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_tribusur-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_tribusur-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_kunstmann-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_kunstmann-config.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_mistral-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_mistral-config.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_sidrareal-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_sidrareal-config.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_milochoochentayocho-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_milochoochentayocho-config.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - mcdonalds-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "mcdonalds-config.FbAdStatsVideoToBigQueryPipeline"


RESULT=$?
ENDTIME=$(date +%s)
echo "Result: $RESULT"
echo "Ending run: `date`"
echo "Processing time: $((ENDTIME - STARTTIME)) seconds"