#!/bin/bash
JAVA=java
JAR=${JARDIR}loaders_dna-bundled-0.5.jar
#CONFIG_FILE = "-config.properties"

STARTTIME=$(date +%s)
echo "Starting today daily run - API to BigQuery: `date`"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - -config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - -config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - -config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - -config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - -config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - -config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - -config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - -config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - -config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - -config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - -config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - -config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - -config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - -config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - -config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - -config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - -config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_warsteiner-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_warsteiner-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_imperial-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_imperial-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_amstel-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_amstel-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_budweiser-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_budweiser-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_cervezamiller-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezamiller-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_cervezapalermo-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezapalermo-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_cervezasalta-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasalta-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_cervezasantafe-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasantafe-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_cervezasol-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_cervezasol-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"



echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_grolsch-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_grolsch-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"


echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-01 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-01" -to "2019-01-01" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-02 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-02" -to "2019-01-02" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-03 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-03" -to "2019-01-03" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-04 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-04" -to "2019-01-04" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-05 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-05" -to "2019-01-05" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-06 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-06" -to "2019-01-06" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-07 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-07" -to "2019-01-07" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-08 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-08" -to "2019-01-08" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-09 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-09" -to "2019-01-09" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-10 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-10" -to "2019-01-10" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-11 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-11" -to "2019-01-11" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-12 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-12" -to "2019-01-12" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-13 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-13" -to "2019-01-13" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-14 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-14" -to "2019-01-14" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-15 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-15" -to "2019-01-15" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-16 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-16" -to "2019-01-16" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"
echo"________________________________________________________________________________________________________________________________________________________"
echo "2019-01-17 - ccu_growlerbar-config.properties"
$JAVA -jar $JAR -from "2019-01-17" -to "2019-01-17" -overwrite-data false -replace-data true -concurrent false -configFileName "ccu_growlerbar-config.properties" -runners "com.dna.app.etl.apitobigquery.facebook.FbAdStatsVideoToBigQueryPipeline"

RESULT=$?
ENDTIME=$(date +%s)
echo "Result: $RESULT"
echo "Ending run: `date`"
echo "Processing time: $((ENDTIME - STARTTIME)) seconds"